precompile(Tuple{typeof(Givre.main)})
precompile(Tuple{Type{Givre.Exit}, Int64})
precompile(Tuple{CooperativeTasks.var"#_exec#33"{Givre.var"#11#12"}})
precompile(Tuple{typeof(Base.eltype), Type{SPIRV.Pointer{Givre.RectangleData}}})
precompile(Tuple{typeof(Dictionaries.set!), Dictionaries.Dictionary{DataType, SPIRV.SPIRType}, Type{Givre.RectangleData}, SPIRV.StructType})
precompile(Tuple{typeof(Dictionaries.set!), Dictionaries.Dictionary{DataType, SPIRV.SPIRType}, Type{SPIRV.Pointer{Givre.RectangleData}}, SPIRV.PointerType})
precompile(Tuple{typeof(Core.convert), Type{DataType}, Type{Givre.RectangleData}})
precompile(Tuple{typeof(Core.convert), Type{DataType}, Type{SPIRV.Pointer{Givre.RectangleData}}})
precompile(Tuple{CooperativeTasks.var"#_exec#35"{CooperativeTasks.LoopExecution, Givre.var"#9#10"{Givre.Application, Givre.Renderer}}})
precompile(Tuple{Givre.var"#3#6"{Givre.Application, Lava.Resource}})
