precompile(Tuple{typeof(Anvil.main)})
precompile(Tuple{Type{Anvil.Exit}, Int64})
precompile(Tuple{CooperativeTasks.var"#_exec#33"{Anvil.var"#11#12"}})
precompile(Tuple{typeof(Base.eltype), Type{SPIRV.Pointer{Anvil.RectangleData}}})
precompile(Tuple{typeof(Dictionaries.set!), Dictionaries.Dictionary{DataType, SPIRV.SPIRType}, Type{Anvil.RectangleData}, SPIRV.StructType})
precompile(Tuple{typeof(Dictionaries.set!), Dictionaries.Dictionary{DataType, SPIRV.SPIRType}, Type{SPIRV.Pointer{Anvil.RectangleData}}, SPIRV.PointerType})
precompile(Tuple{typeof(Core.convert), Type{DataType}, Type{Anvil.RectangleData}})
precompile(Tuple{typeof(Core.convert), Type{DataType}, Type{SPIRV.Pointer{Anvil.RectangleData}}})
precompile(Tuple{CooperativeTasks.var"#_exec#35"{CooperativeTasks.LoopExecution, Anvil.var"#9#10"{Anvil.Application, Anvil.Renderer}}})
precompile(Tuple{Anvil.var"#3#6"{Anvil.Application, Lava.Resource}})
